"""update is_ready

Revision ID: 1480116d1620
Revises: d0ad6119c089
Create Date: 2019-08-17 13:58:30.499284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1480116d1620'
down_revision = 'd0ad6119c089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download', sa.Column('is_ready', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download', 'is_ready')
    # ### end Alembic commands ###
