"""empty message

Revision ID: 309e1ee0850d
Revises: 
Create Date: 2019-08-02 20:01:38.243750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309e1ee0850d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taggpx', sa.Column('hash_url', sa.String(length=256), nullable=True))
    op.add_column('taggpx', sa.Column('zip_folder', sa.String(length=256), nullable=True))
    op.drop_column('taggpx', 'result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taggpx', sa.Column('result', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('taggpx', 'zip_folder')
    op.drop_column('taggpx', 'hash_url')
    # ### end Alembic commands ###
