"""empty message

Revision ID: 5d63de994830
Revises: 9c028e040006
Create Date: 2019-08-09 12:47:18.586595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d63de994830'
down_revision = '9c028e040006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping', 'color',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('mapping', 'tiles',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping', 'tiles',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('mapping', 'color',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
