"""Add download table

Revision ID: 6035206527cb
Revises: 43ef49d216a2
Create Date: 2019-08-16 17:39:29.624523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6035206527cb'
down_revision = '43ef49d216a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download', 'user_id')
    # ### end Alembic commands ###
