"""funcking harder

Revision ID: 7df90f739105
Revises: 21a4b4c4ced9
Create Date: 2019-08-09 13:27:47.665103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df90f739105'
down_revision = '21a4b4c4ced9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('tiles', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(timezone=128), nullable=True),
    sa.Column('zip_folder', sa.String(length=256), nullable=True),
    sa.Column('hash_url', sa.String(length=256), nullable=True),
    sa.Column('send_by_email', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('taggpx', sa.Column('map', sa.Boolean(), nullable=True))
    op.add_column('taggpx', sa.Column('send_by_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.drop_column('taggpx', 'send_by_email')
    op.drop_column('taggpx', 'map')
    op.drop_table('mapping')
    # ### end Alembic commands ###
