"""add more time information to TagGPX

Revision ID: b2e5c4245ae9
Revises: 1480116d1620
Create Date: 2019-08-17 15:03:06.769772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e5c4245ae9'
down_revision = '1480116d1620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('folder_mapping', sa.String(length=64), nullable=False),
    sa.Column('folder_gpx', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('tiles', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(timezone=128), nullable=True),
    sa.Column('download_file', sa.String(length=256), nullable=True),
    sa.Column('hash_url', sa.String(length=256), nullable=True),
    sa.Column('send_by_email', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taggpx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('time_difference', sa.Integer(), nullable=True),
    sa.Column('half_hour', sa.Integer(), nullable=True),
    sa.Column('time_ref', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('created', sa.DateTime(timezone=128), nullable=True),
    sa.Column('download_file', sa.String(length=256), nullable=True),
    sa.Column('hash_url', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('send_by_email', sa.Boolean(), nullable=True),
    sa.Column('map', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taggpx')
    op.drop_table('mapping')
    op.drop_table('users')
    op.drop_table('download')
    # ### end Alembic commands ###
