"""empty message

Revision ID: b7f3ed6e5433
Revises: f45d766ef951
Create Date: 2019-08-12 19:02:17.521511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f3ed6e5433'
down_revision = 'f45d766ef951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taggpx', sa.Column('time_difference', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taggpx', 'time_difference')
    # ### end Alembic commands ###
