"""empty message

Revision ID: c04752972a91
Revises: 309e1ee0850d
Create Date: 2019-08-09 12:32:05.213373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04752972a91'
down_revision = '309e1ee0850d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('tiles', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(timezone=128), nullable=True),
    sa.Column('zip_folder', sa.String(length=256), nullable=True),
    sa.Column('hash_url', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapping')
    # ### end Alembic commands ###
