"""empty message

Revision ID: cffc723ae91d
Revises: 0d86c85f3e38
Create Date: 2019-08-16 17:51:35.173165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffc723ae91d'
down_revision = '0d86c85f3e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download', sa.Column('project_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download', 'project_name')
    # ### end Alembic commands ###
