"""add ready flag to download table

Revision ID: d0ad6119c089
Revises: 85e63cd3139d
Create Date: 2019-08-17 13:43:07.705118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ad6119c089'
down_revision = '85e63cd3139d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'finished')
    op.drop_column('taggpx', 'finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taggpx', sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mapping', sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
