"""add download folder column

Revision ID: f45d766ef951
Revises: 7df90f739105
Create Date: 2019-08-09 16:07:48.179785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45d766ef951'
down_revision = '7df90f739105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('download_file', sa.String(length=256), nullable=True))
    op.drop_column('mapping', 'zip_folder')
    op.add_column('taggpx', sa.Column('download_file', sa.String(length=256), nullable=True))
    op.drop_column('taggpx', 'zip_folder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taggpx', sa.Column('zip_folder', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('taggpx', 'download_file')
    op.add_column('mapping', sa.Column('zip_folder', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('mapping', 'download_file')
    # ### end Alembic commands ###
