version:          "3.7"

services:
  # Creates a service called myp
  myp:
    build:
      context:    ./services/myp
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    env_file:
      - app-prod.env
    # Same name as the service name
    depends_on:
      - myp-db

  # Builds DB from local costum db image
  myp-db:
    build:
      context:    ./services/myp/app/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - db-prod.env
  # nginx setup
  nginx:
    build:
      context:    ./services/nginx
      dockerfile: Dockerfile-prod
    restart:      always
    ports:
      - 80:80
    depends_on:
      - myp
